### ISSUE TITLE
required version of google-cloud-storage needs bumping

### ISSUE THREAD

**Issue by will-moore** [allenai/cached_path#106]
## Checklist

- [ ] I have verified that the issue exists against the `main` branch.
- [ ] I have read the relevant section in the [contribution guide](https://github.com/allenai/cached_path/blob/main/CONTRIBUTING.md#bug-reports-and-feature-requests) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/cached_path/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/cached_path/pulls) for existing proposed fixes.
- [ ] I have checked the [CHANGELOG](https://github.com/allenai/cached_path/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/cached_path/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ ] I have included in the "Environment" section below the output of `pip freeze`.
- [ ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

I already had `google-cloud-storage` Version: `1.31.0` installed when I installed `cached_path`, which satisfies the requirements 
`google-cloud-storage>=1.0,<3.0` in https://github.com/allenai/cached_path/blob/main/requirements.txt

However, when I try to import `cached_path` I get the exception below because that version of `google-cloud-storage` is out of date: `No module named 'google.cloud.storage.retry'.

I don't know what version of `google-cloud-storage` added this, but if I do `pip install -U google-cloud-storage` the error goes away.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
  File "/Users/wmoore/Desktop/ZARR/ome-zarr-py/ome_zarr/reader.py", line 7, in <module>
    from cached_path import cached_path
  File "/Users/wmoore/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/cached_path/__init__.py", line 13, in <module>
    from ._cached_path import cached_path
  File "/Users/wmoore/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/cached_path/_cached_path.py", line 15, in <module>
    from .schemes import get_scheme_client, get_supported_schemes, hf_get_from_cache
  File "/Users/wmoore/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/cached_path/schemes/__init__.py", line 3, in <module>
    from cached_path.schemes.gs import GsClient
  File "/Users/wmoore/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/cached_path/schemes/gs.py", line 11, in <module>
    from google.cloud.storage.retry import DEFAULT_RETRY
ModuleNotFoundError: No module named 'google.cloud.storage.retry'
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: M1 Mac

Python version: 3.9.12

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
$ pip show google-cloud-storage
Name: google-cloud-storage
Version: 1.31.0
Summary: Google Cloud Storage API client library
Home-page: https://github.com/googleapis/python-storage
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/wmoore/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages
Requires: google-auth, google-cloud-core, google-resumable-media
Required-by: cached-path

```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

**Comment by epwalsh** [comment]
Thanks for bringing this up @will-moore! I'll do some digging.

**Comment by epwalsh** [comment]
Looks like this module was [first introduced in v1.32.0](https://github.com/googleapis/python-storage/blob/v1.32.0/google/cloud/storage/retry.py), so I'll make that the minimum version.

**Comment by will-moore** [comment]
Great, thanks!
