### ISSUE TITLE
Dependency clash between latest Transformers release and cached_path

### ISSUE THREAD

**Issue by sidharthrajaram** [allenai/cached_path#206]
Are there plans to remove the dependency constraint on [huggingface-hub < 0.19.0](https://github.com/allenai/cached_path/blob/main/pyproject.toml#L27)?

The latest releases of Hugging Face's Transformers API rely on attributes (namely, `huggingface_hub.constants.HF_HUB_CACHE`) that are only defined in the latest release of huggingface-hub. 

As a result, the constraint in this library is leading to a situation where a dependency on _latest_ Transformers release and cached_path cannot be resolved.

Thank you!

**Comment by epwalsh** [comment]
Hey @sidharthrajaram no problem, CI is passing with the latest HF-hub so I'll cut a new release of `cached-path` with that right now.

**Comment by epwalsh** [comment]
Closed via [v1.5.1](https://github.com/allenai/cached_path/releases/tag/v1.5.1).
